atraylor/frontpage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.SectionList.as_view(), name='home'),
]

atraylor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('atraylor.frontpage.urls')),
]

atraylor/frontpage/models.py
from django.db import models

# Create your models here.
CONTENT_STATE = ((0, 'Editing'),
                 (1, 'Published'))
                                                                                                                                                                             
class Section(models.Model):
    title = models.CharField(verbose_name='Title', max_length=200)
    order = models.IntegerField(verbose_name='Order', default=999)
    
    class Meta:
        ordering = ['order']

class Content(models.Model):
    parent = models.ForeignKey(Section, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Title', max_length=200, unique=True)
    order = models.IntegerField(verbose_name='Order')
    slug = models.CharField(verbose_name='Slug', max_length=200, unique=True)
    peek = models.IntegerField(verbose_name='Number Of Characters To Preview')
    body = models.TextField(verbose_name='Body')
    creation_datetime = models.DateTimeField(verbose_name='Creation Datetime', auto_now_add=True)
    last_update_datetime = models.DateTimeField(verbose_name='Last Update Datetime', auto_now=True)
    state = models.IntegerField(verbose_name='State', choices=CONTENT_STATE, default=0)

    class Meta:
        ordering = ['order']

atraylor/frontpage/views.py
from django.utils import timezone
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import Section, Content

# Create your views here.
class SectionList(ListView):
    model = Section

atraylor/frontpage/templates/banner.html
{% block banner %}
{% load static %}
    <div class="banner-wrapper">
        <img class="banner" src="{% static '/images/banner-light.jpg' %}" style=" width: 100%;" id="banner">
        <img class="headshot" src="{% static '/images/headshot1.png' %}" height="40%">
        <div class ="nameplate outlined">Alexander Traylor
            <span class="nameplate title">Developer</span>
            <a class="nameplate cv no-outline" href="#">Download Resume</a>
        </div>
    </div>
{% endblock %}

atraylor/frontpage/templates/frontpage/section_list.html
{% block content %}
    <head>
        {% load static %}
        <link rel="stylesheet" href="{% static '/css/materialize.css' %}">
        <script type="text/javascript" src="{% static '/js/materialize.js' %}"></script>
        <script>
            var darkbanner="{% static '/images/banner-dark.jpg' %}"
            var lightbanner="{% static '/images/banner-light.jpg' %}"
        </script>
        <script type="text/javascript" src="{% static '/js/main.js' %}"></script>
    </head>
    <body>
    {% block navbar %}{% include 'navbar.html' %}{% endblock %}
        <div class="wrapper" style="position: relative;">
        {% block banner %}{% include 'banner.html' %}{% endblock %}
	</div>
        {% for section in object_list %}
            <div class="container">
                <div class="card">
		    <span class="card-title">{{ section.title }}</span>
                    <div class="card card-body">
			<ul class="tabs">
                        {% for content in section.content_set.all %}				
      	                {% if content.state == 1 %}
                            <li class="tab"><a href="#content_body{{ content.id }}"><b>{{ content.title }}</b></a></li>
                        {% endif %}
    			{% endfor %}
			</ul>

			{% for content in section.content_set.all %}
			{% if content.state == 1 %}
		        <div id="content_body{{ content.id }}" style="margin-left: 40px;">
                        {% if content.body|length > content.peek and content.peek != 0 %}
                            {{ content.body|linebreaks|slice:content.peek }}...
                            <a class="more_less" id="{{ content.id }}" href="#!">Read More</a>
	                    <div hidden id="full{{ content.id }}">{{ content.body|linebreaks }}</div>
                        {% else %}
	                    {{ content.body|linebreaks }}
        	        {% endif %}
			{% endif %}
		        </div>
			{% endfor %}
                    </div>
                </div>
            </div>
	</div>
        {% endfor %}
</body>
    <footer>
        <div id="attribmodal" class="modal">
            <div class="modal-content">
              <h4>Attribution</h4>
              <p><b>Light Mode Banner:</b> <a href="https://www.pexels.com/photo/flock-of-birds-917494/" target="_blank">Flock Of Birds</a> by <a href="https://www.pexels.com/@efdal-yildiz-325089" target="_blank">Efdal YILDIZ</a>, used under <a href="https://www.pexels.com/license/" target="_blank">the Pexels License</a> / Cropped From Original</p>
              <p><b>Dark Mode Banner:</b> <a href="https://www.flickr.com/photos/bz3rk/7076919551/in/album-72157607107822110/" target="_blank">Charlotte Skyline</a> by <a href="https://www.flickr.com/photos/bz3rk/0" target="_blank">James Willamor</a>, used under <a href="https://creativecommons.org/licenses/by-sa/2.0/legalcode" target="_blank">CC BY-SA 2.0</a> / Cropped From Original</p>
            </div>
            <div class="modal-footer">
              <a href="#!" class="btn modal-close waves-effect waves-green btn-flat">Acknowledge</a>
            </div>
        </div>
        <div class="container">
            <p class="left-align">I built this resumé using Django - Check out the source <a href="https://gitlab.com/agtraylor/resume" target="_blank">here</a>!</p>
            <p class="right-align"><a class="modal-trigger" href="#attribmodal">Image Attribution</a></p>
        </div>
    </footer>
{% endblock %}

atraylor/frontpage/templates/sidebar.html
{% block sidebar %}
    <div class="col-md-4 float-right ">
        <div class="card my-4">
            <h5 class="card-header">About Us</h5>
            <div class="card-body">
                <p class="card-text"> This awesome blog is made on the top of our Favourite full stack Framework 'Django', follow up the tutorial to learn how we made it..!</p>
                <a href="https://djangocentral.com/building-a-blog-application-with-django"
                    class="btn btn-danger">Know more!</a>
            </div>
        </div>
    </div>
{% endblock sidebar %}

templates/navbar.html
{% block navbar %}
{% load static %}
    <div class="navbar-fixed">
	<script src="https://kit.fontawesome.com/2c366abe5a.js" crossorigin="anonymous"></script>
        <nav>
            <div class="nav-wrapper">
                <div class="valign-wrapper left" style="height: 100%; padding-left: 10;">
                    <div class="switch valign ">
                        <label>
                        Light
                        <input type="checkbox" id="mode_toggle">
                        <span class="lever"></span>
                        Dark
                        </label>
                    </div>
                </div>
                <div class="valign-wrapper center">
                   <a class="valign" onclick="M.toast({html: 'Reserved For Future Use'})" href="#!"><img class="valign center tagline" src="{% static '/images/terminal.gif' %}">
                    </a>
                </div>
                <div class="valign-wrapper right" style="height:100%; right:90;">
                    <a class="valign" href="https://gitlab.com/agtraylor" target="_blank"><i class="fab fa-gitlab"></i></a>
                    <a class="valign" href="https://www.linkedin.com/in/alextraylor/" target="_blank"><i class="fab fa-linkedin"></i></a>
                    <a class="valign" href="mailto:alex.traylor@gmail.com"><i class="far fa-envelope"></i></a>
                    <a class="valign hide-on-large-only" href=tel:+17049572091><i class="fas fa-mobile-alt"></i></a>
                </div>
                </div>
            </div>
        </nav>
    </div>
{% endblock %}